# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11ef92de4dca2447c8356937674e4f144e047ffc1cfa975c2c1e8affd3c2db019dec264f7516357918cf55421906269329a7eee70cbb52a8a2de2595d130713c

test:
  secret_key_base: 54ca449812bdc61b0e06e7eb2dd484a18340d58eca4ad2ef50d19147d9eeccc3addcf7842da96ab53a1b6f923f86c701d9f9168e9a175b2db00e1d1e43134f17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
